[FacelessDetectionIncome.X2DLCInfo_FacelessDetectionIncome]
DLCIdentifier="FacelessDetectionIncome"

[FacelessDetectionIncome CHModDependency]
DisplayName="FacelessDetectionIncome"

+RequiredMods=LongWarOfTheChosen
+RequiredMods=X2WOTCCommunityHighlander

[XComGame.UIScreenListener]
+ScreenListeners=UIListener_FacelessIncome

;+IncompatibleMods="DLCIdentifier_Of_Some_Mod_A"

;+RequiredMods="WOTCIridarTemplateMaster"

;+IgnoreRequiredMods="DLCIdentifier_Of_Some_Mod_F"

; Commonly used modnames:

; PrototypeArmoury
; CovertInfiltration
; LongWarOfTheChosen
; XCOM2RPGOverhaul
; X2WOTCCommunityPromotionScreen
; PrimarySecondaries
; TruePrimarySecondaries
; DualWieldedPistols
; WOTC_LW2SecondaryWeapons


[FacelessDetectionIncome CHDLCRunOrder]
;+RunAfter=DLCIdentifier_A
;+RunBefore=DLCIdentifier_D

;RunPriorityGroup=RUN_FIRST
;RunPriorityGroup=RUN_STANDARD
;RunPriorityGroup=RUN_LAST